from .diggingEnvironment import diggingEnvironment
from .flyingEnvironment import flyingEnvironment
from .swimmingEnvironment import swimmingEnvironment
from .walkingEnvironment import walkingEnvironment