from .ant import Ant
from .bettaFish import BettaFish
from .copperhead import Copperhead
from .earthworm import Earthworm
from .finch import Finch
from .gerbil import Gerbil
from .mouse import Mouse
from .parakeet import Parakeet
from .rattlesnake import Rattlesnake
from .terrapin import Terrapin